app:
  bootstrap-server:
    ip-address: "127.0.0.1"
    port: 55555
    timeout: 10000
    node-name: "node-{uniqueID}"
  commands:
    register-format: "REG %s %s %s"
    un-register-format: "UNREG %s %s %s"
    message-format: "%04d %s"
  node:
    max-neighbours: 6
    min-neighbours: 2
  common:
    r-ping-message-id: "rPingMessage"
spring:
  main:
    web-application-type: none