app:
  bootstrap-server:
    ip-address: "127.0.0.1"
    port: 55555
    timeout: 10000
    ping-interval: 8000
    ping-timeout: 3000
    ping-retry: 3
  commands:
    register-format: "REG %s %s %s"
    un-register-format: "UNREG %s %s %s"
    message-format: "%04d %s"
    leave-format: "LEAVE %s %s"
    join-format: "JOIN %s %s %s"
    joinok-format: "JOINOK %s %s"
    pong-format: "PONG %s %s"
    ping-message-id-format: "PINGID:%s:%s"
    query-format: "SER %s %s %s %s"
    query-hit-format: "SEROK %s %s %s %s %s"
    ping-format: "PING %s %s"
  node:
    node-name: "node-{uniqueID}"
    max-neighbours: 6
    min-neighbours: 2
    join-hop-limit: 3
    hop-count: 5
  common:
    r-ping-message-id: "rPingMessage"
    file-name: "FileNames.txt"
    enable-console: false
server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: "./src/main/resources/distributed-file-sharing-app.p12"
    key-store-password: 1qaz2wsx!QAZ@WSX
    enabled: true